version: "3.9"

services:
  nginx:
    image: nginx:alpine
    container_name: secure-crud-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - private_net

  app:
    build: .
    container_name: secure-crud-app
    env_file:
      - ./src/.env
    depends_on:
      - mongo
    networks:
      - private_net

  mongo:
    image: mongo:7
    container_name: secure-crud-mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - private_net

volumes:
  mongo_data:

networks:
  private_net:
    driver: bridge